pdf_documents = [
    {
        "content": """2 Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016

Die Errichtung von dezentralen Energieanlagen ist in der Praxis oft mit Konflikten belastet, denen vielfältige und sehr unterschiedliche Aspekte zugrunde liegen können. Dennoch wird vielfach versucht, diese Konflikte vereinfachend mit dem „NIMBY-Syndrom“ (Not In My Backyard) zu erklären und herunter zu spielen oder ihnen mit dem vermeintlichen Königsweg der frühzeitigen Bürgerbeteiligung zu begegnen. Allerdings werden derartige Engführungen in der öffentlichen Debatte und auch in der Fachliteratur der Komplexität des Problems nicht gerecht. Auf der Basis von drei ausgewählten Beispielen (zwei Windparks, eine Biogasanlage) werden im Folgenden zehn Aspekte beschrieben, die Konflikte um derartige Anlagen entstehen und eskalieren lassen können.

2.1 Zu wenig und zu späte Beteiligung

Planungs- und Genehmigungsverfahren werden häufig mit den Argumenten kritisiert, sie böten zu wenig oder zu späte Öffentlichkeitsbeteiligung. Diese Kritik ist darauf zurückzuführen, dass Bürger häufig erst auf konkrete Vorhaben aufmerksam werden, wenn sich diese bereits in der Genehmigungs- oder gar Realisierungsphase befinden. Da zu diesem Zeitpunkt keine gestaltende Beteiligung mehr möglich ist und die existierenden Formen der Öffentlichkeitsbeteiligung als wenig bürgerfreundlich wahrgenommen werden, werden mehr und eine frühere Öffentlichkeitsbeteiligung gefordert.

Tatsächlich sind jedoch nicht nur im immissionsschutzrechtlichen Genehmigungsverfahren, sondern bereits auf den verschiedenen vorgeschalteten Planungsebenen Beteiligungen der Öffentlichkeit vorgesehen. Richtungsweisende Entscheidungen fallen schon auf diesen Planungsstufen. Diese beschäftigen sich abstrakt mit der Frage, „Ob“ und „Wo“ bestimmte Raumnutzungen stattfinden sollen und können. Auf dieser Ebene geht es noch nicht um konkrete Windenergieanlagen, sondern um die Aufgabe, im Planungsraum Flächen für die Windenergienutzung auszuweisen und gegebenenfalls gleichzeitig auf den nicht ausgewiesenen Flächen die Nutzung der Windenergie auszuschließen. Diese Entscheidungen sind anschließend nicht mehr Gegenstand der weiteren Verfahren.

Aufgrund der Abschichtung von Entscheidungen in aufeinanderfolgenden Verfahren verengen sich jeweils der Entscheidungsgegenstand und damit auch die Gestaltungs- und Einflussmöglichkeiten der Öffentlichkeit. Wer sich erst im Genehmigungsverfahren beteiligt, kann – wenn überhaupt – nur noch die Antwort auf die Frage beeinflussen, „Wie“ ein Vorhaben umgesetzt wird.

Aufgabe des Planungsrechts ist es, konkurrierende Ansprüche an den Raum in Einklang zu bringen und für die Zukunft zu gestalten. Hierbei wird zwischen überörtlicher und örtlicher Planung unterschieden. Planungsentscheidungen werden jeweils durch demokratisch legitimierte Organe getroffen, in der Regionalplanung durch Regionalversammlungen oder ähnliche überörtlich konstituierte Gremien und in der Bauleitplanung durch Gemeinderäte oder Gemeindevertretungen. Diese demokratisch legitimierten Organe treffen ihre Entscheidung im Rahmen einer planerischen Abwägung über die im Plangebiet geltend gemachten öffentlichen und privaten Belange. Dieses Abwägungsgebot ist ein komplexer Willensbildungsprozess, der sich durch die Gestaltungsfreiheit des Trägers der Planungshoheit auszeichnet. Dadurch gibt es kein zwingend vorgegebenes Ergebnis der Planung. Die Planungsentscheidungen richten sich vielmehr nach den vorgegebenen Gewichtungen im Abwägungsprozess. Die Öffentlichkeit kann während des Planungsverfahrens ihre Belange – privater oder öffentlich-rechtlicher Natur – gegenüber den entsprechenden Gremien artikulieren. Diese haben ausreichend weite Entscheidungsspielräume, um diese zu berücksichtigen.

Im immissionsschutzrechtlichen Genehmigungsverfahren besteht hingegen kein Entscheidungsspielraum der Behörde. Vielmehr hat sie die Genehmigung zu erteilen, wenn die gesetzlichen Voraussetzungen erfüllt sind, und unpersönlich, objektiv und nach allgemein angewandten Kriterien zu entscheiden. Je nach Kapazität, Anzahl und Größe der dezentralen Energieanlagen ist im Verfahren eine Öffentlichkeitsbeteiligung durchzuführen. Bei Windenergieanlagen sind förmliche Verfahren mit Öffentlichkeitsbeteiligung jedoch eher die Ausnahme.

Obwohl damit mehrere Möglichkeiten für Bürger bestehen, ihre Interessen geltend zu machen, wird diese Möglichkeit, wenn überhaupt, oft erst im Genehmigungsverfahren wahrgenommen. Dann sind aber viele Fragen bereits in den vorhergehenden Verfahrensstufen entschieden worden. Dies verursacht bei den Bürgern große Frustration, wenn sie das Vorhaben grundsätzlich und umfassend erörtern wollen.

Beispiel W.:

W. ist eine vom Tourismus lebende Gemeinde, die sich durch die Regionalplanung mit fünf großen Vorranggebieten für die Nutzung von Windenergie rund um den Ort konfrontiert sieht. Der Bürgermeister von W. sieht ein, dass die Kommune angesichts der Windhöffigkeit keine Chance hat, ganz ohne Windparks davon zu kommen. Er zeigt sich daher verhandlungsbereit und bietet der Regionalplanungsbehörde an, zwei oder drei der geplanten Windparks in weniger für den Tourismus sensiblen Bereichen zu unterstützen, indem er auf die skeptischen Eigentümer zugeht. Die anderen Gebiete sollten dann aber als Vorranggebiete aus der Regionalplanung aufgrund eines neuen Tabu-Kriteriums „Tourismus“ herausgenommen werden.

Die Regionalplanung macht deutlich, dass es hierfür keinen rechtlichen Spielraum gibt. Auf die betreffenden Flächen hat die Gemeinde keinen Zugriff und im immissionsschutzrechtlichen Genehmigungsverfahren spielt der Tourismus keine Rolle, solange es keine nachweisbare existenzielle Bedrohung für einzelne Unternehmen gibt. Dass die Kommune schon bei einem Rückgang des Tourismus um 10 bis 20 % massive finanzielle Probleme bekommen wird, spielt im formalen Verfahren keine Rolle.""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 7-9",
        "category": "participation"
    },
    {
        "content": """2.2 Wirkungslose frühe Öffentlichkeitsbeteiligung

Um die Bürgerbeteiligung bei der Durchführung von Großprojekten zu stärken und der in der Praxis geäußerten Kritik zu später Öffentlichkeitsbeteiligung entgegenzutreten, hat der Bundesgesetzgeber 2013 eine frühe Öffentlichkeitsbeteiligung im Verwaltungsverfahrensgesetz (VwVfG) ermöglicht. Nach dem neu eingefügten § 25 Abs. 3 VwVfG soll die Genehmigungsbehörde darauf hinwirken, dass bei Vorhaben, die nicht nur unwesentliche Auswirkungen auf die Belange einer größeren Zahl von Dritten haben können, die betroffene Öffentlichkeit über das geplante Vorhaben informiert und ihr Gelegenheit zur Stellungnahme gegeben wird. In welcher Form und in welchem Ausmaß die Behörde auf die Durchführung der frühen Öffentlichkeitsbeteiligung hinwirkt, liegt in ihrem Ermessen.

Die betroffene Öffentlichkeit soll möglichst frühzeitig über das Vorhaben informiert werden. Wann der beste Zeitpunkt für die Durchführung der frühen Öffentlichkeitsbeteiligung gegeben ist, lässt sich nicht einheitlich für alle von der Norm erfassten Vorhaben bestimmen. Aus der Formulierung, dass eine Öffentlichkeitsbeteiligung „möglichst“ frühzeitig stattfinden soll, ist jedoch zu schließen, dass sie grundsätzlich dann erfolgen soll, wenn das Vorhaben noch nicht in allen Einzelheiten festgelegt ist und es noch Gestaltungsmöglichkeiten gibt. So kann es sich anbieten, die frühe Öffentlichkeitsbeteiligung mit dem Scoping-Termin oder einem Raumordnungsverfahren zu verknüpfen, gerade wenn für das Vorhaben noch nicht alle Ausgestaltungsdetails festgelegt wurden.

Allerdings besteht keine Pflicht des Vorhabenträgers, der Hinwirkung der Behörde nachzukommen und eine frühe Öffentlichkeitsbeteiligung durchzuführen. Insofern ist es für das später durchzuführende Genehmigungsverfahren auch unerheblich, ob eine frühe Öffentlichkeitsbeteiligung durchgeführt wurde oder nicht und ob diese ordnungsgemäß erfolgt ist. Denn die Regelung zielt nur darauf ab, durch frühzeitigen Informationsaustausch die Gestaltung von Großvorhaben zu optimieren, Transparenz zu schaffen und die Akzeptanz von Genehmigungs- und Planfeststellungsentscheidungen zu fördern.

Damit die frühe Öffentlichkeitsbeteiligung aber ihre Transparenz- und Akzeptanzfunktion erreichen kann, muss der Vorhabenträger bereit sein, Zeit und Kosten in die Durchführung einer frühen Öffentlichkeitsbeteiligung zu investieren und ernsthaft am Gespräch auf Augenhöhe interessiert sein. Dies kann die Behörde nicht erzwingen.

Kann die Einführung einer frühen Öffentlichkeitsbeteiligung durch den Gesetzgeber mit der Intention, die Transparenz und Akzeptanz in Genehmigungsverfahren zu stärken, zwar grundsätzlich als positiv gewertet werden, so ergeben sich in der Praxis im Hinblick auf das Erreichen dieses Ziels jedoch erhebliche Unsicherheiten, da der Anwendungsbereich der Vorschrift sehr offen formuliert ist. Zudem hängt die Durchführung der frühen Öffentlichkeitsbeteiligung von der Einwirkungskraft der Behörden und dem Willen des Vorhabenträgers ab und es bleibt fraglich, ob die frühe Öffentlichkeitsbeteiligung in der Praxis überhaupt zum Einsatz kommen wird.

Das Beispiel B.:

Gemeinde und Projektierer sind sich einig: Die Flächennutzungsplanung weist die Fläche aus, die sich der Projektierer gesichert hat. Die Flächeneigentümer haben sich zu einer Poollösung zusammengeschlossen und stehen hinter dem Verfahren. Nun gründet sich eine Bürgerinitiative im Ortsteil N. Der Vorhabenträger stellt sein Vorhaben im Vorfeld des Genehmigungsantrags in B. öffentlich vor (im Sinn einer frühzeitigen Beteiligung). Da das Vorhaben bereits durchkalkuliert ist, beschränkt er sich aber auf Information. Es wären möglicherweise im Detail noch Anpassungen möglich, aber die Bürgerinitiative lehnt den Windpark im Ganzen ab. Die Vorstellung des Projekts ist als Infomarkt konzipiert, die vielen bislang unbeteiligten Bürgern in B. Informationen zur Verfügung stellt. Den Konflikt mit der Initiative in N. kann er nicht beeinflussen.""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 10-11",
        "category": "procedure"
    },
    {
        "content": """2.3 Zu geringe Gestaltungsmöglichkeiten in den Verfahren

Grundsätzlich besteht in den Planungsverfahren auf regionaler und kommunaler Ebene die Möglichkeit, sich als interessierter Bürger in die Entscheidungsfindung einzubringen. Der Steuerung der Windenergienutzung auf kommunaler Ebene sind allerdings aufgrund der Vorgaben der Landesplanungsgesetze und durch eine ausdifferenzierte höchstrichterliche Rechtsprechung Grenzen gesetzt – eine „Nulllösung“ für Kommunen, in denen Politik und Bevölkerung die Windenergieanlagen ablehnen, kann auf kommunaler Ebene nicht umgesetzt werden. Die Planungsträger müssen der Windenergie substanziellen Raum verschaffen. Positiv- und Negativausweisungen bedingen einander. Für beide müssen belastbare Kriterien gefunden werden und nur, wenn positive Flächen für die Windenergienutzung identifiziert werden, kann auch eine Negativausweisung erfolgen.

Aufgrund der Überlagerung verschiedener raumrelevanter Kriterien (Mindestabstand zu Siedlungsflächen, die Berücksichtigung naturschutzfachlicher Schutzräume, etwa bei Vögeln oder Fledermäusen, die Berücksichtigung von Abstandsregeln etwa bei Denkmälern, Funkfeuern oder Sendemasten) bleiben in der Regel oft nur sehr wenige Flächen für die Nutzung der Windenergie übrig. Können keine Flächen für die Nutzung identifiziert werden, ist es auf kommunaler Ebene der Gemeinde verwehrt, für das Gemeindegebiet die Windenergienutzung vollständig auszuschließen.

Kommt es nicht zur planerischen Ausweisung von Konzentrationszonen für die Nutzung der Windenergie, so ist diese aufgrund der bauplanungsrechtlichen Privilegierung in § 35 Abs. 1 Nr. 5 BauGB im Außenbereich grundsätzlich zulässig. Vorhabenträger können dann direkt immissionsschutzrechtliche Anträge stellen. Dies ist mit Aussicht auf Erfolg sogar dann möglich, wenn sich ein Flächennutzungsplan in der Aufstellung befindet und sich bereits Positivausweisungen konkretisiert haben. Die Kommune kann die Anträge zwar befristet für ein Jahr zurückstellen lassen, eine dauerhafte Blockade mittels unvollendeter Flächennutzungspläne ist jedoch nicht möglich. Gerade das Zurückstellen von Bauanträgen wird die Gemeinde aber dann nicht wählen, wenn sie selbst Eigentümerin der Flächen ist und von den Pachteinnahmen profitiert. Denn dann ist sie daran interessiert, dass die Pachteinnahmen früh fließen.

Für den Planungsträger besteht somit zwar grundsätzlich ein Entscheidungsspielraum, doch sind die Entscheidungsmöglichkeiten rechtlich stark eingeengt. Eine Kommune, die keine Flächen für die Windenergienutzung ausweisen will, unterliegt der bauplanungsrechtlichen Privilegierung. Der gesamte Außenbereich steht somit für die Nutzung der Windenergie offen. Sie kann die Errichtung von Windenergieanlagen auch auf eigenen Flächen nur dann verhindern, wenn öffentliche Belange der konkreten Nutzung entgegenstehen. Dies ist im jeweiligen Einzelfall zu prüfen. Um in den Genuss der Ausschlusswirkung des § 35 Abs. 3 Satz 3 BauGB zu gelangen, muss die Kommune mindestens eine Fläche, die auch für die Windenergienutzung geeignet ist, ausweisen. Weist sie eine Fläche aus, die wirtschaftlich nicht genutzt werden kann, ist die Planung rechtswidrig und es gilt die Vorschrift des § 35 Abs. 1 BauGB, nach der unter bestimmten Voraussetzungen die Errichtung eines Bauwerks im Außenbereich zulässig ist.

Sobald absehbar ist, ob und wenn ja welche Flächen ausgewiesen werden, bemühen sich Projektierer darum, für diese Flächen Optionsverträge abzuschließen. Angesichts hoher Pachtforderungen der Eigentümer, schwierig einschätzbarer naturschutzfachlicher Auflagen und der Unsicherheit über die zukünftigen Förderbedingungen im Rahmen des Erneuerbare-Energien-Gesetzes (EEG) sind Projektierer in der Regel wenig gewillt, sich auf gestaltende Beteiligungsprozesse einzulassen.

Auf die engen Grenzen für gestaltende Beteiligung treffen Erwartungen aus der Öffentlichkeit, wonach die Öffentlichkeitsbeteiligung eine Mitentscheidung ermöglichen soll. Frustrationen dieser Erwartungen sind „vorprogrammiert“.

Das Beispiel F.:

Die hessische Regionalplanung hat die landesplanerische Vorgabe, 2 Prozent der Landesfläche als Vorranggebiet für die Windenergienutzung auszuweisen. Der im Entwurf befindliche Teilregionalplan Energie für Nordhessen weist im Bereich der Gemeinde F. zwei Flächen aus, auf denen sich ein Projektierer den Zugriff gesichert hat. Die Gemeinde möchte – unterstützt durch eine Bürgerinitiative – eine dieser beiden Flächen (A) aus dem Regionalplan herausnehmen und bietet stattdessen eine andere Fläche (B) an, auf der bereits ältere Windenergieanlagen stehen und Platz für weitere Anlagen wäre. Allerdings sieht die zuständige Regionalplanungsbehörde diese Fläche aufgrund benachbarter FFH-Gebiete als nicht geeignet an.

Der Investor wäre bereit, die bereits erteilte Genehmigung des Windparks am Standort A ruhen zu lassen, wenn er im Gegenzug die Möglichkeit erhielte, am Standort B einen erfolgversprechenden Antrag zu stellen. Die Regionalplanungsbehörde sieht keine Möglichkeit, die Flächen an der Autobahn als Vorranggebiete auszuweisen. Auf der Fläche A hat der Investor bereits auf eine von sechs geplanten Windenergieanlagen verzichtet und ein geplantes Umspannwerk verlegt. Er ist auch zu Verhandlungen mit der Bürgerinitiative über die Betriebsführung bereit. Die Bürgerinitiative will aber nur in eine Mediation eintreten, wenn der gesamte Park auf den Prüfstand gestellt wird. Aufgrund der jeweils beschränkten Gestaltungsmöglichkeiten besteht selbst für einigungswillige Partner kaum eine Möglichkeit, sich zu einigen.""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 13-14",
        "category": "planning"
    },
    {
        "content": """2.4 Mangelnde Nachvollziehbarkeit von Verfahren

Für interessierte Bürger ist es schwer zu erkennen, an welcher Stelle sich ein Verfahren befindet und welche Beteiligungsmöglichkeiten konkret bestehen.

Standorte von Windenergieanlagen werden je nach Bundesland über die Regionalplanung oder über die Flächennutzungsplanung gesteuert. Auch bei der Regionalplanung sind Bürgermeister und Abgeordnete aus der Region an der Erarbeitung des Plans und damit an der Festlegung der Flächen für die Windenergienutzung beteiligt. Bürger werden hierüber jedoch kaum informiert. Ist dies doch der Fall, können sie im Zuge der Öffentlichkeitsbeteiligung eine Stellungnahme abgeben. In der Regel beteiligen sich jedoch wenige Bürger an der Regionalplanung – es sei denn, es ist bereits ein Konflikt in einer bestimmten Region des Plangebietes ausgebrochen, der die Bürger zur Abgabe von – oft tausendfach kopierten – Stellungnahmen bewegt.

Wer nicht ohnehin „im Thema“ ist, sieht sich mit einem Plan konfrontiert, der im Kartenteil sich überlagernde farbige, schraffierte oder gepunktete „Kleckse“ und Symbole enthält und im Textteil diese Symbole in einer spezifischen, für Laien schwer nachvollziehbaren Sprache der Planer beschreibt.

Aber auch wenn ein Gebiet für die Windenergienutzung in der eigenen Region identifiziert werden kann, ist noch immer nicht hinreichend klar, welche Flächen hiervon konkret betroffen sind. Der Regionalplan enthält keine flächenscharfen Ausweisungen, um nicht in die Planungshoheit der Gemeinden einzugreifen – und auch die Konzentrationszonen im Flächennutzungsplan lassen den genauen Standort möglicher Windenergieanlagen noch offen. Außerdem bleibt die Frage, ob auf dem vorgesehenen Areal überhaupt Windenergieanlagen errichtet werden, wenn ja, wie viele es werden, wie hoch sie sein werden, und wer sie betreiben wird. Dabei würde es sich lohnen, gerade an dieser Stelle schon zu intervenieren, denn rechtlich gesehen besteht hier die größte Einflussmöglichkeit.

Interessierte Bürger, die es jedoch nicht gewohnt sind, Regional- oder Flächennutzungspläne zu lesen und sich die möglichen Anlagen bildlich vorzustellen, werden große Schwierigkeiten haben, sich auf dieser Planungsebene einzubringen. Es ist ein grundsätzliches Problem, dass sinnlich nachvollziehbare Übersetzungen der Planungsideen und ihrer Auswirkungen fehlen. Gäbe es solche, könnte die Öffentlichkeit ihre Beteiligungsmöglichkeiten bereits auf diesen Planungsebenen nutzen. Fundamentalkritik würde gegebenenfalls weniger verfangen, da die Menschen eher wüssten, was auf sie zukommt.

Nach Abschluss der Planung oder auch parallel hierzu strengt ein Vorhabenträger ein immissionsschutzrechtliches Verfahren an, an dem allerdings erst ab 20 Windenergieanlagen die Öffentlichkeit zwingend zu beteiligen ist. Bei weniger Anlagen werden, wenn keine Umweltverträglichkeitsprüfung erforderlich ist, im vereinfachten Verfahren nur direkte Nachbarn informiert. Aber egal ob öffentliches Verfahren oder nicht: Die für einen interessierten Bürger hilfreiche sequentielle Folge (erst planerische Ausweisung und nahe daran anschließend dann Genehmigungsverfahren) ist in der Praxis selten. Entweder sind seit der Diskussion um den Regionalplan Jahre vergangen und kaum jemand erinnert sich an die Debatte, oder die Verfahren laufen parallel und es werden bereits Genehmigungen erteilt, bevor der Plan rechtskräftig ist. Wer sich im Verfahren der Öffentlichkeitsbeteiligung an der Bauleit- oder Regionalplanung im gesetzlich vorgesehenen Rahmen beteiligt, wird es nur schwer verstehen, dass auf den als Vorrang- oder Konzentrationszonen auszuweisenden Flächen Fakten geschaffen werden, bevor der Plan rechtskräftig wird. Oder aber es gibt keinen Plan und die Bürger werden erstmalig mit dem Thema konfrontiert, wenn ein Genehmigungsantrag zur Errichtung von Windenergieanlagen gestellt ist.

Wer sich an den formalen Verfahren beteiligen will, muss einen Stapel Aktenordner durchlesen: komplexe Pläne, Bauzeichnungen, Lärmberechnungen, Artenschutzlisten und viel Text, der sich durch technische und juristische Fachbegriffe auszeichnet. Kaum jemand, der nicht zumindest semi-professionell damit zu tun hat, findet sich hier zurecht. Selbst die Kurzfassungen für die Öffentlichkeit sind oft wenig verständlich. Und wie sollen Bürger verstehen, dass es bezüglich der Einhaltung von Lärmrichtwerten Gesprächsmöglichkeiten mit der Behörde und dem Vorhabenträger gibt (z.B. Monitoringmaßnahmen, Abschaltzeiten), über den Wertverlust der eigenen Immobilie aber nicht verhandelt werden kann, dass beim Lärm gerechnet, aber nicht gemessen wird? Es ist die Rede von Dauerschallpegeln, von Infraschall, von logarithmischen Skalen. Prognosen stellen keine Basis dafür dar, sich vorzustellen, wie laut es in der Realität im eigenen Vorgarten werden wird. Experten können sich aus den Plänen, Formeln und technischen Beschreibungen in ihrem Kopf ein Bild über eine künftige Anlage machen. Für Laien ist dies ausgeschlossen.

Fotomontagen zeigen den Blick von ausgewählten Standorten. Aber die betroffenen Bürger haben eine stärker subjektive Sicht der Dinge und fragen sich, wie die Anlage aus der Perspektive des eigenen Wohnzimmerfensters oder des lieb gewonnenen Spazierwegs wirkt, wie der Lärm bei wechselndem Wind oder entlang bevorzugter Fußwege erlebt wird, welche Wirkungen er auf besonders empfindliche Menschen oder auf ruhesuchende Touristen hat oder wie sich die Anlagen auf durchziehende Zugvögel auswirken. Als Folge dieser komplizierten Verfahrens- und Fachfragen wird es den „Profis“ überlassen, die Debatte zu führen. Diese können Vorhabenträgern und Behörden Paroli bieten.

Planung und Genehmigung werden von unterschiedlichen Behörden betreut, es findet häufig keine übergreifende und vor allem keine kontinuierliche Kommunikation und Information während des Prozesses der Planungs- und Genehmigungsverfahren statt. Der Prozess leidet auch unter seiner zeitlichen Länge. Einerseits sind die unterschiedlichen Planungsstufen und Genehmigungsstufen miteinander verschränkt und erwecken bei den Bürgern den Eindruck einer einzuhaltenden Stufenfolge, die viel Zeit in Anspruch nimmt. Findet beispielsweise vor der Bauleitplanung eine frühzeitige Öffentlichkeitsbeteiligung statt, kann es im Einzelfall mehrere Monate bis zu wenigen Jahren dauern, bis die immissionsschutzrechtliche Öffentlichkeitsbeteiligung im Genehmigungsverfahren folgt. Dazwischen ist die Öffentlichkeit uninformiert. Andererseits ist es den Bürgern nicht zu vermitteln, dass die Verfahren nicht streng nacheinander ablaufen müssen, sondern parallel angestoßen werden können und sobald sich Flächen für eine Ausweisung auf der Planungsebene konkretisieren, Anträge auf Zulassung von Windenergieanlagen gestellt werden können.

Das Beispiel S.:

Aufstellungsbeschluss und frühzeitige Öffentlichkeitsbeteiligung zum Teil-Flächennutzungsplan Windenergie führten in der Öffentlichkeit und im Gemeinderat kaum zu kontroversen Diskussionen. In der ersten Offenlegung waren drei Standorte vorhanden – die potenziell betroffenen Anwohner nahmen davon kaum Notiz. Erst als klar wurde, dass zwei der drei Standorte wegfallen würden und ein Projektierer für den übrig bleibenden Standort auf den Plan trat, erhob sich Protest im Ortsteil G. Nur fünf Einwohner von G. hatten sich in der frühzeitigen Öffentlichkeitsbeteiligung zu Wort gemeldet. Erst als im Laufe des Verfahrens Visualisierungen ins Spiel kamen, zeichnete sich eine breitere Beteiligung der Bevölkerung in G. ab.""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 15-19",
        "category": "procedure"
    },
    {
        "content": """2.5 Unterschiedliche Logiken von und in der Planung

Planungsträger folgen bestimmten politischen und administrativen und zum Teil ökonomischen Logiken. Sich beteiligende Bürger gehen zumeist mit einer anderen Rationalität an die Diskussion heran, sie verlangen Ergebnisoffenheit, Deliberation und Mitsprachemöglichkeiten.

Die Planung ist für Bürger nicht nur komplex und schwer verständlich, sie folgt auch nicht unbedingt der Logik, die aus Bürgersicht angebracht wäre. Planungen im Hinblick auf die Steuerung von Windenergieanlagen sind nicht ergebnisoffen. Es muss substanziell Raum für die Windenergie geschaffen werden, um eine Steuerungswirkung in Form von Konzentrationszonen und Ausschlussgebieten zu erreichen. Dagegen äußern Bürger immer wieder, dass auch die Nulloption Teil des Beteiligungsraums sein muss.

Kommunen, die eigene Flächen nutzen oder für die Nutzung zur Verfügung stellen, stellen häufig ökonomische Betrachtungen an. Angesichts knapper Haushalte können sie ihre finanziellen Spielräume erweitern, indem sie auf eigenen Flächen selbst Anlagen errichten oder Nutzungsrechte an eigenen Flächen verpachten. Eine frühzeitige Verpachtung von Flächen eröffnet den Gemeinden häufig die Option, teure Gutachten im Rahmen der Flächennutzungsplanung durch die potenziellen Vorhabenträger finanzieren zu lassen. Ein Teil der sehr komplexen Planung von Konzentrationszonen, die Gemeinden in der Praxis häufig auch überfordert, wird damit von den Schultern der Gemeinde genommen. Dies entlastet die Gemeindekasse zusätzlich und legt die zum Teil schwierige Erstellung avifaunistischer Gutachten in die Hände der Vorhabenträger.

Die Entscheidung, Flächen zu verpachten, bevor die Flächennutzungsplanung abgeschlossen ist und konkrete Flächen für die Windenergienutzung ausgewiesen wurden, kann auf Seiten der Bürger dazu führen, dass sie die Flächennutzungsplanung als Alibiplanung betrachten, an der sie zwar beteiligt werden, bei der sie aber überhaupt keinen Einfluss haben, da bereits Pachtverträge existieren. Ein solches Vorgehen der Kommunen ist den Bürgern schwer zu vermitteln und sorgt für Konflikte, wenn es vor Abschluss des Pachtvertrages nicht hinreichend kommuniziert wird.

Viele Kommunen verzichten nicht zuletzt aus ökonomischen Gründen darauf, das Instrument der Flächennutzungsplanung für die Steuerung der Windenergienutzung einzusetzen. Dies stellt sich dann weniger als Problem dar, wenn eine funktionierende Regionalplanung existiert. Dann wirken die Ziele der Raumordnung auch auf kommunaler Ebene und erreichen eine Steuerung der Windenergieanlagen. Existiert hingegen keine funktionierende Regionalplanung und auch keine Flächennutzungsplanung, erfolgt die Prüfung der Standortfrage allein auf der Ebene der immissionsschutzrechtlichen Genehmigung.

Den Bürgern ist schwer zu vermitteln, dass keine Pflicht der Gemeinden besteht, Flächen für die Windenergienutzung zu planen. Noch schwieriger scheint die Situation, den Bürgern zu vermitteln, wenn in benachbarten Gemeinden unterschiedliche Vorgehensweisen gewählt werden, indem eine Gemeinde einen Flächennutzungsplan zur Steuerung der Windenergienutzung aufstellt, die andere jedoch nicht. Selbst wenn benachbarte Kommunen windhöffige Flächen in Grenzlage haben, besteht keine Pflicht für eine einheitliche Vorgehensweise oder eine Zusammenarbeit. Die Pflicht zur Rücksichtnahme nach § 2 Abs. 2 Satz 1 BauGB verhindert nicht, dass Bürger einer planenden Gemeinde mit Anlagen auf der Gemarkung der Nachbargemeinde konfrontiert werden, für die keine Planung vorliegt. Die Vorgehensweise der planenden Gemeinde, in ihrem Gebiet eine Steuerung der Anlagen vorzunehmen, wird aus Sicht der Bürger dadurch konterkariert, dass die Anlagen auf dem Gebiet der Nachbargemeinde errichtet werden, die Betroffenheit letztlich aber identisch wahrgenommen wird.

Das alles führt dazu, dass die juristische, administrative und ökonomische Logik der Kommune häufig gegen die Bürgerlogik der Anwohner steht.

Das Beispiel S.:

In S. war bereits zu Beginn der Bauleitplanung absehbar, dass die gemeindeeigenen Flächen am Standort A aufgrund ihrer Windhöffigkeit und aufgrund geringer naturschutzfachlicher Bedeutung mit hoher Wahrscheinlichkeit am Ende des Prozesses als Konzentrationszonen ausgewiesen würden. Um die Kosten für die im Rahmen des Flächennutzungsplanverfahrens erforderlichen Gutachten für die Gemeinde gering zu halten, verhandelte die Kommune bereits frühzeitig mit verschiedenen Projektierern und schloss dann mit einem Unternehmen einen Optionsvertrag für die Pacht dieser Flächen. Diese aus ökonomischen Gründen sinnhafte Vorgehensweise, die auch nicht verschwiegen, sondern öffentlich kommuniziert wurde, wurde später bei den betroffenen Anwohnern zum Gegenstand heftiger Kritik, die Kommune sei von Anfang an in ihrer Planung nicht ergebnisoffen gewesen.""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 20",
        "category": "stakeholders"
    },
    {
        "content": """2.6 Beteiligungsparadox

Auch wenn der Öffentlichkeit die Unterschiede und der Verfahrensablauf von Planungs- und Genehmigungsverfahren bekannt sind, kann sie von der Abstraktheit der einzelnen Verfahren überfordert sein. Sie ist dann nicht in der Lage, die Möglichkeiten, sich zu beteiligen, korrekt einzuordnen. Insbesondere auf der Planungsebene, wo eine wirksame Beteiligung zu „Ob“ und „Wo“ angedachter Vorhaben noch möglich ist, erscheinen die Planungen zu abstrakt und die Betroffenheit wird nicht wahrgenommen. Erkennen Bürger ihre Betroffenheit, ist meist bereits die Ebene der konkreten Vorhabengenehmigung erreicht und sie können sich dann nur noch zu Fragen des „Wie“ des Vorhabens beteiligen.

Viele Bürger bemerken erst, dass ein Vorhaben ihre Lebenssituation berührt, wenn gerodet und planiert wird, Fundamente betoniert und Teile des Turms oder Rotorblätter herbeitransportiert werden. Die Windenergieanlagen werden aufgestellt und erst jetzt sehen die Bürger, welche Ausmaße das Projekt wirklich hat. Viele Menschen fangen erst jetzt an zu fragen, wer Vorteile durch die Windenergieanlagen hat. Wer investiert? Wer profitiert? Was bekommen die Flächeneigentümer, was bleibt in der Gemeindekasse?

Für die gestuften Verfahren und ihre jeweilige Öffentlichkeitsbeteiligung zeigt sich eine paradoxe Situation: Je einflussreicher die Beteiligung wäre, desto abstrakter ist der Verfahrensgegenstand und desto geringer ist die Wahrnehmung der Betroffenheit. Je konkreter ein Vorhaben wird und je stärker die Bürger ihre Betroffenheit bemerken, desto geringer sind die Möglichkeiten, auf ein Vorhaben noch Einfluss zu nehmen.

Es ist zwar auf allen Planungs- und Genehmigungsebenen eine Öffentlichkeitsbeteiligung vorgesehen, sie entfaltet aber gerade auf den Planungsebenen nur geringes Mobilisierungspotenzial. Auf Ebene des immissionsschutzrechtlichen Genehmigungsverfahrens entsteht der Eindruck, dass die Entscheidung über das Vorhaben bereits gefallen ist, obwohl erst auf dieser Ebene eine Öffentlichkeitsbeteiligung möglich zu sein scheint.

Ergebnis dieses Paradox ist eine Frustration der Öffentlichkeit, da die Möglichkeiten zur Beteiligung – selbst wenn sie verstanden würden – aufgrund des Abstraktionsniveaus der Verfahrensinhalte nicht sinnvoll ausgeübt werden können. Dies begründet ein Gefühl, ungerecht behandelt zu werden.

Das Beispiel S.:

In S. ging einem immissionsschutzrechtlichen Genehmigungsverfahren von Windenergieanlagen die Aufstellung eines Flächennutzungsplans voraus. Bereits auf dieser Ebene wurden wegweisende Entscheidungen für die Ansiedlung von Windenergieanlagen im Gemeindegebiet getroffen. Das Interesse der Bürger war während des Planungsverfahrens eher gering. So bearbeitete die Planungsbehörde nur wenige Stellungnahmen. Der Bürgerprotest erreichte allerdings seinen Höhepunkt während des immissionsschutzrechtlichen Genehmigungsverfahrens – nachdem die konkreten Standorte der Windenergieanlagen bekannt wurden.

Während des immissionsschutzrechtlichen Genehmigungsverfahrens wurden beispielsweise Bedenken hinsichtlich des Tourismus vorgebracht. Diese sind nicht Teil des immissionsschutzrechtlichen Prüfprogramms. Die Bürger haben den auf Planungsebene zu berücksichtigenden Einwand zu spät geäußert, so dass er nicht mehr entscheidungsrelevant war. Man bezeichnet diesen Effekt als Bulldozer-Effekt.""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 21-23",
        "category": "participation"
    },
    {
        "content": """2.7 Legitimer Eigennutz vs. NIMBY-Interessen

Typisch für die öffentliche und zum Teil auch wissenschaftliche Interpretation von Beteiligungskonflikten ist die Lesart, dass es sich bei der Ablehnung von dezentralen Energieanlagen überwiegend um NIMBY-Verhalten handelt. Mit dieser Argumentation wird die Tatsache, dass sich Personen um ihre ureigenen Interessen kümmern, als „borniertes Hinterhofdenken“ dargestellt, das sich in Widerspruch zum Gemeinnutz des Projekts oder der Energiewende stellt. Demnach würden Bürger dezentrale Energieanlagen nur solange befürworten, wie sie nicht selbst von ihnen betroffen sind. Mitunter wird in der öffentlichen Diskussion jede Art von Oppositionsverhalten gegenüber geplanten Projekten pauschal mit NIMBY-Motiven erklärt.

Zunächst handelt es sich bei dieser Charakterisierung um eine Vereinfachung, die der Vielfalt der Gründe, die es gegen ein Projekt geben kann, nicht gerecht wird. Wo beginnt eigentlich der Hinterhof und wo hört er auf? Was verbirgt sich hinter dem Begriff der egoistischen Motive? Immerhin handeln die Betroffenen nach rationalen Nutzenkalkülen und damit im Sinne der in den Sozial- und Wirtschaftswissenschaften dominierenden Handlungstheorien. Insofern ist es verständlich und legitim, dass sich Personen gegen Projekte wehren, wenn sie etwa einen Wertverlust ihres Eigentums befürchten.

Das Beispiel B.:

Bei einem Konflikt wegen Biogasanlagen in B. äußert ein betroffener Anwohner sehr klar seine Gründe für das Engagement in der Bürgerinitiative: „Ich möchte meine Ruhe haben! Ich habe mir hier in guter schwäbischer Manier vor dreißig Jahren ein Einfamilienhaus zu einem bestimmten Preis gekauft, und ich möchte nicht, dass dieses an Wert verliert, weil die Terrasse nicht mehr so idyllisch ist, wenn dort künftig zwanzig Traktoren mehr vorbeifahren.“

Trotzdem gilt, dass dezentrale Energieanlagen nicht nur aus eigennützigen Motiven abgelehnt werden. Häufig steht nicht ein individueller Vor- oder Nachteil durch ein Projekt im Vordergrund, sondern die wahrgenommene Verfahrens- und Verteilungsgerechtigkeit. Es kann also durchaus in einem allgemeinen Sinn darum gehen, wer von einem Projekt profitiert, wer die Nachteile zu tragen hat und inwiefern ein Lastenausgleich stattfindet. Zudem beeinflusst der Gestaltungs- und Mitentscheidungsspielraum der Bürger die Wahrnehmung von Projekten. Standortausweisungen für Windenergieanlagen können immer auch Verlierer und Härtefälle hervorbringen. Dies kann sowohl Neidgefühle wecken als auch Konflikte innerhalb von Ortschaften oder zwischen Gemeinden verursachen. Daher sind transparente und faire Verfahren der Entscheidungsfindung wichtig.

Das Beispiel W.:

Bei der Planung eines Windparks in der Gemeinde W. sind eigentlich alle Beteiligten an einer konfliktfreien Planung und Durchführung interessiert, weil die Hoffnung besteht, dass die strukturschwache Region durch die zu erwartenden ökonomischen Vorteile gewinnt. Aber der künftige Betreiber spricht – ohne jede Transparenz dieses Vorgehens – bereits vor der Ausweisung von Windvorranggebieten mit einzelnen Grundstückeigentümern und bietet Optionsverträge an. In der Wahrnehmung derjenigen, die nicht in diese Vorgespräche involviert sind, die also keinen Vertrag angeboten bekommen haben und die sich deshalb benachteiligt fühlen, werden die Betreiber als „Heuschrecken“ wahrgenommen, die die „Naivität der Gemeinden und der Bevölkerung“ ausnutzen, um die Gemeinden zu „spalten“.""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 24-25",
        "category": "tradeoffs"
    },
    {
        "content": """2.8 Getarnte und latente Motive

Die Bandbreite der Faktoren, die die Wahrnehmung und Bewertung von dezentralen Energieanlagen beeinflussen, ist groß. Es kann um Umwelt- und Naturschutzbelange gehen, um die spezifische technische Gestaltung der Anlagen, um Standortfragen, um erwartete negative Folgen durch visuelle Einflüsse, Störgeräusche, Geruchsbelästigungen bis hin zu zusätzlichem Verkehrsaufkommen. Dabei handelt es sich häufig um kontroverse, meist jedoch um sachlich beschreibbare, messbare und in Gutachten überprüfbare Aspekte.

Die Wahrnehmung von vorgesehenen dezentralen Energieanlagen wird aber auch von emotional motivierten Aspekten beeinflusst – etwa die Sorge vor Veränderung des Landschaftsbilds und damit der Heimat. Eingriffe in die als unberührt erlebte Landschaft und befürchtete Veränderungen der Ortsidentität sind immer wieder Auslöser von lokaler Ablehnung. Auch Neid gehört zu den Emotionen.

Derartige kollektiv-emotionale Aspekte können in rechtlich geregelten Verfahren, die auf objektive Überprüfbarkeit angewiesen sind, kaum offiziell eingebracht werden. Dies gilt insbesondere für Genehmigungsverfahren. Hier können nur Individualinteressen geltend gemacht werden, die sich in „subjektiv öffentlichen Rechten“ widerspiegeln. Das Recht auf eine unberührte Landschaft oder Heimat gehört zum Beispiel nicht dazu. Aber auch formal adressierte Rechte wie Gesundheit oder Schutz des Eigentums werden nur im Rahmen konkretisierender Rechtsnormen (z. B. TA Lärm) oder eindeutig nachweisbarer Effekte berücksichtigt. Wenn es, wie beim Wertverlust von Immobilien, nur um die Sorge vor oder die geringe Wahrscheinlichkeit von negativen Beeinträchtigungen geht oder wenn aufgrund der Ausweisung eines Wohngebiets als Mischgebiet höhere Lärmrichtwerte erlaubt sind, stehen die Chancen schlecht, dies im Genehmigungsverfahren thematisieren zu können.

Die fehlende Möglichkeit, emotionale oder symbolisch aufgeladene Themen in Genehmigungsverfahren einbringen zu können, bewirkt Exklusion. Dies kann dazu führen, dass die eigentlichen Motive, gegen ein Projekt zu opponieren, verdeckt und andere, die in Rechtsform gebracht werden können, vorgeschoben werden. In der Theatermetapher gesprochen: Die Akteure treten maskiert auf.

Ein weiteres Beispiel für verdeckte oder auch latente Motive stellen Überlagerungseffekte des aktuellen Konflikts mit Auseinandersetzungen in der Vergangenheit dar. Die gleiche Bürgerinitiative, die sich anlässlich eines völlig anderen Themas konstituiert hat, tritt nun erneut als Partei im Konflikt um eine geplante Anlage in Erscheinung. Ein ähnliches Hineinspielen der Vergangenheit ist auch aus anderen Praxisfällen der Beteiligung bekannt.

Das Beispiel B.:

In B. ging dem Konflikt um eine Biogasanlage viele Jahre vorher ein Konflikt um die Ansiedlung eines Discounters voraus. Die Frontlinien von damals werden im Konflikt um die Biogasanlage wieder aktualisiert. Von den Gegnern der Anlage wurden die in der Region verwurzelten Befürworter der Anlage als traditionell und wenig kompetent wahrgenommen: „Ich habe mich bei Kommunalwahlen als freier Bürger ohne Parteizugehörigkeit allein beworben. Ich habe mich vorgestellt in den Versammlungen der anderen Parteien und zwar hatte ich ein einziges Ziel: Dem Bürgermeister und den Gemeinderäten ordnungsgemäßes Rechnen, kaufmännisches Denken zu vermitteln, was offensichtlich hier stark im Defizit lag.“

Aber auch die Seite der Befürworter hat klare Bilder von der Gegenseite. Es handele sich um „großkotzige ehemalige Geschäftsführer und Manager, die jetzt daheim hocken, nichts zu tun haben und ihre Freizeit damit verbringen, uns zu drangsalieren“. Die Etikettierung als Zugezogene findet klaren Ausdruck in der Äußerung: „Das sind diese Garagentordrücker! – die haben mit B. nicht mehr zu tun, als dass sie von der Autobahn runterfahren, die automatische Garagentür öffnen, ins Haus rein und dann ist fertig.“ Tatsächlich liegt also hinter dem Energiekonflikt ein Sozialkonflikt.""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 26-27",
        "category": "stakeholders"
    },
    {
        "content": """2.9 Milieuspezifische Verhärtung von Positionen

Das geschilderte Phänomen – der in der Gruppe geteilte Bezug auf miteinander durchgestandene Auseinandersetzungen in der Vergangenheit – weist auf gemeinsame Hintergrundmotive hin, die sowohl für eine gemeinsame Position im vergangenen als auch in dem gegenwärtigen Konflikt über die Energieanlage sorgen und nicht unbedingt in der Sache selbst liegen – Motive also, die im einen wie im anderen Konflikt zu einer gemeinsamen Grundhaltung führen. Das ist typisch für Haltungen sozialer Milieus. Diese sind dann auch mit klaren Selbst- und Fremdbildern verbunden.

Das Gefühl intransparenter Verfahren, vorab entschiedener Fragen, unberücksichtigter Interessen und unwirksamer Mitwirkung kann dazu führen, dass die Betroffenen sich unfair behandelt fühlen oder mangelnde Fairness behaupten. Sie bestreiten dann die Legitimation von Verfahren zur Genehmigung von Windenergieanlagen. Mitunter eskalieren Bürger bewusst, um Unterstützung zu finden und Vertreter der Politik zur Einflussnahme auf die Verfahren zu drängen.

Bei lokalen Protesten gegen dezentrale Energieanlagen wird aktiver Widerstand meist von kleinen Gruppen Aktiver initiiert. Sie bilden den Kristallisationspunkt von Bürgerinitiativen gegen geplante Projekte. Obwohl zahlenmäßig klein, besitzen sie über ihr soziales Netzwerk eine enorme Mobilisierungsfähigkeit. Es handelt sich in der Regel um sozial gut Gestellte mittleren oder höheren Alters, mit hoher Formalbildung und (ehemals) gehobener beruflicher Stellung, häufig Männer mit naturwissenschaftlich-technischer Ausbildung. Für diese „aktiven Eliten“ gilt ein Teil der bisher genannten Defizite aufgrund ihrer quasi-professionellen Befassung mit den Verfahren nicht.

Die von ihnen geprägten Haltungen gegen dezentrale Energieanlagen können sich zu Elementen des milieuspezifischen Selbst- und Fremdbildes verdichten. Diese führen zu verhärteten Positionen, die nicht ohne Gesichtsverlust aufgegeben werden können. Gegenüber der jeweils anderen Gruppe wird mit Etikettierungen gearbeitet, die nicht nur Schichtunterschiede signalisieren, sondern deutliche symbolische Distinktionen beinhalten. In den Fallbeispielen zeigt sich, dass die Kerngruppen des Protests dazu neigen, sich in die Rolle der Fundamentalopposition zu begeben.

Die Auseinandersetzung wird zum Kristallisationskern milieuspezifischen Zusammengehörigkeitsgefühls. Eine andere Meinung zu haben, wird zum Verrat und mit sozialem Ausschluss geahndet. Jetzt wird das soziale Milieu zum Eskalationsmilieu. Die Bereitschaft, sich pragmatisch mit dem Konfliktgegenstand auseinanderzusetzen, an Kompromissen mitzuarbeiten und gegebenenfalls von der eigenen Position abzurücken, ist gering. Um die eigenen Interessen durchzusetzen, ist die Bereitschaft hoch, auch Gründe gegen ein Projekt ins Feld zu führen, die nicht unbedingt den eigenen Intentionen entsprechen und letztlich alle Mittel, die die Verfahrensbeteiligungen bieten, auszureizen. In sozialen Milieus verankerte Fundamentalopposition kann dazu führen, dass Konflikte sich so verhärten, dass lokale Gemeinschaften dauerhaft in Projektbefürworter und -gegner gespalten werden.

Das Beispiel B.:

Der Konflikt in B. ist so zugespitzt, dass die Forscherin des Projekts Dezent Zivil, anstatt das Interview in einer Gastwirtschaft durchzuführen, in eine Privatwohnung gebeten wird, wo dann Tacheles geredet wird. Die Befürworter seien in Kneipen-Seilschaften eingebunden, in denen intransparente Entscheidungen ausgekungelt würden. „Das ist ein Netzwerk in einer Gemeinde. Und ein Bürgermeister muss sich sehr schnell – das ist seine einzige Überlebenschance – diesem Netzwerk anschließen. Und das Netzwerk in B. wird bestimmt – heute noch – von Landwirten ... . In einer solchen Gemeinde ist die Mehrheit der Gemeinderäte von der Gunst des Bürgermeisters abhängig … . Weil die alle irgendwo ein Grundstück haben, was zu Bauland wird … . Die wichtigste Information bzw. Meinungsbildung, die findet nicht im Gemeinderat statt, die findet in der Nachsitzung im L. statt“ (Gastwirtschaft).""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 28-29",
        "category": "conflict_dynamics"
    },
    {
        "content": """2.10 Defizitäre Interaktion und Kommunikation

Wenn in einer Gemeinde oder Region ein Konflikt um eine dezentrale Energieanlage entsteht, geht es für viele (noch) unbeteiligte Zuschauer schnell um die Frage, wie das Vorhaben bewertet wird – positiv oder negativ. Damit verbunden ist dann auf beiden Seiten häufig die Neigung zur Personalisierung, die in die Frage mündet, wer der Böse und wer der Gute ist. Bürgerinitiativen zeichnen das Bild einer friedlichen Region, die vom Vorhabenträger angegriffen wird. Umgekehrt fühlt sich der Vorhabenträger von den Initiativen angegriffen. Unterstützer und Gegner entwickeln wechselseitig ähnliche Bilder.

In dieser Situation gibt es Vorhabenträger, die den Weg des „Augen zu und durch“ wählen, schließlich haben sie einen Rechtsanspruch auf Genehmigung. Soll jedoch eine Eskalation vermieden und mit Interessengegensätzen fair umgegangen werden, bedarf es in einer solchen Situation eines vertrauenswürdigen Dritten, der das Gespräch ermöglicht. Denn, wer auch immer sich als „Opfer“ sieht, ihm fällt es schwer, das ehrliche und faire Gespräch mit dem „Angreifer“ zu suchen.

Ob der Bürgermeister oder eine vergleichbare Person die Rolle des vertrauenswürdigen Dritten erfüllen kann, ist zu diskutieren. Oft ist zu beobachten, dass das Gemeindeoberhaupt als „Retter“ angerufen wird oder sich selbst als solcher sieht – entweder des Vorhabenträgers gegen die Initiativen oder umgekehrt. Gleichzeitig hat er eigene Interessen. Und durch das sich „auf eine Seite schlagen“ ist die Rolle des vertrauenswürdigen Dritten auch schnell verspielt. Wenn die Bürgerinitiativen den Konflikt im Genehmigungsverfahren eskalieren, das „Spielfeld“ der formellen Verfahren verlassen haben und direkt an die Politik appellieren, tendieren sie dazu, Gemeinderat und Bürgermeister, die nicht auf ihrer Seite sind, die Gemeinwohlorientierung abzusprechen und sich als „wahre“ Vertreter des „Volkes“ zu sehen.

Eigentlich sollte die Genehmigungsbehörde die Rolle des vertrauenswürdigen Dritten ausfüllen. Doch die meisten Behördenvertreter sind dafür weder ausgebildet noch geschult. Sie sehen es in der Regel auch nicht als ihre Aufgabe an, in der Öffentlichkeit aufzutreten und zwischen verfeindeten Konfliktparteien zu vermitteln. Selbst wenn sie es als ihre Aufgabe begreifen, fehlen ihnen zeitliche Ressourcen und Kompetenzen.

Aufgrund des Austausches über das Verfahren ist das Genehmigungsverfahren oft durch die Kommunikation zwischen dem Vorhabenträger und der Behörde geprägt. Dadurch wird häufig die Neutralität der Behörde in Frage gestellt, indem ihr eine gewisse Nähe zum Vorhabenträger unterstellt wird. Die Öffentlichkeitsbeteiligung in Zulassungsverfahren wird als Pflichtübung absolviert. Sie dient keiner der mit ihr verfolgten Funktionen und die ihr zugedachte Ausgleichs- und Befriedungsfunktion kann sie nicht wahrnehmen. Ferner „mauern“ sich Projektträger und Zulassungsbehörde gegenüber der Öffentlichkeit ein.

Gerade im Erörterungstermin stehen sich Gegner und Befürworter eines Vorhabens oft unversöhnlich gegenüber. Ein Aufeinanderzugehen der Konfliktparteien ist zu diesem Zeitpunkt nicht mehr zu erreichen. Der Erörterungstermin wird dann als „Kampfarena“ genutzt, um mit allen rechtlich zur Verfügung stehenden Mitteln gegen das Vorhaben anzukämpfen. Dabei gerät der einzelne Einwender, der seine persönliche Betroffenheit artikulieren möchte, häufig aus dem Blick. Für ihn kann dann der Eindruck entstehen, er habe keine Möglichkeit, seine Einwendungen mit der zuständigen Behörde oder dem Vorhabenträger zu erörtern.

In dieser ohnehin schwierigen Konstellation wiegt jeder Fehler in der Kommunikation und Interaktion doppelt schwer. Abstraktes, kühles, fachliches Auftreten von Behörden und Vorhabenträgern wird als Arroganz und Desinteresse ausgelegt. Ein Behördenvertreter berichtet im Interview: „Da war eine öffentliche Vorstellung in der Gemeindehalle und die Vortragenden waren so was von überheblich und arrogant, dass dort der Protest angefangen hat mit Buhrufen und allem. Die haben keinen Fuß mehr auf den Boden gekriegt. Es war aus ... . Es reicht, wenn Sie den Namen vom Ort falsch aussprechen, oder einen württembergischen Landesteil Baden zuordnen … . Die Sachargumente sind dann weg. Und wenn Sie das machen, sind Sie vor Ort sofort inkompetent und das überträgt sich dann auf alles andere auch.“

Mängel bei der Einladung oder Durchführung von Veranstaltungen werden als bewusste Interventionen interpretiert. Eine schlecht durchgeführte Öffentlichkeitsbeteiligung kann Konflikte auslösen und zu Akzeptanzproblemen führen. Sie verlängert häufig das gesamte Vorhaben, beispielsweise durch Klagen. Umgekehrt werden irritierte und verunsicherte Bürger als NIMBY-Egoisten und „ferngesteuerte Verhinderer“ denunziert. Die gegenseitigen Wahrnehmungen (hier fundamentalistische Wutbürger, dort profitgierige Unternehmen) verstärken sich im Zuge der Konflikteskalation.

Unprofessionelle Veranstaltungsformen und bewusste Eskalationsstrategien, die diese ausnutzen, gehen Hand in Hand. In überfüllten Sälen mit ungeschickt auftretenden Vorhabenträgern auf der Bühne und den Bürgern unten im Saal fällt es Kritikern oft nicht schwer, die anfangs noch Unbeteiligten auf ihre Seite zu ziehen. Die zuschauenden Bürger, vermittelt durch Eigenlogiken der Medien („only bad news are good news“) und der Politik (Positionen müssen zugespitzt werden), werden zunehmend in den Konflikt einbezogen, die Stimmung im Ort polarisiert sich. Ist die Polarisierung erst einmal fortgeschritten, erscheint unfaires Verhalten (gegenüber Nicht-Unterstützern, gegenüber Gegnern) legitim. Als „David“ (Bürgerinitiative) gegenüber „Goliath“ (Vorhabenträger) sind Verfahrenstricks erlaubt, wie etwa das Einfordern von Gutachten zur Verteuerung und Verzögerung des Vorhabens. Umgekehrt nutzen Vorhabenträger alle rechtlichen Möglichkeiten, um voran zu kommen, wie etwa das Ausnutzen eines „unbeplanten Raums“, wenn Bauleitpläne einer Kommune wegen Formfehlern gerichtlich aufgehoben werden. Am Ende unterstellt man sich gegenseitig öffentlich kriminelle und skandalöse Praktiken, was im schlimmsten Fall den Weg für Gewalt eröffnen kann.

Die beschriebenen Entwicklungen sind nicht zwangsläufig. Eskalationen erfolgen nicht automatisch. Und vielfach gibt es innerhalb der Konfliktparteien unterschiedliche Ansichten über die richtige Strategie. Vernünftige, an sachlichen Lösungen und Kompromissen orientierte Akteure fühlen sich unwohl angesichts der sich entwickelnden Fundamentalpositionen. Allerdings führen die Mechanismen der Presseberichterstattung und der politischen Positionierung vielfach dazu, dass sich unbewusste Allianzen von Fundamentalpositionen auf beiden Seiten bilden, die nicht an konstruktiven Lösungen des Konflikts interessiert sind und so zu dessen Verschärfung beitragen.

Das Beispiel K.:

Der Bürgermeister von K. regt an, mit lokalen Akteuren gemeinsam einen Windpark im Ortsteil G. auf die Beine zu stellen. Die Flächeneigentümer sind bereit mitzugehen, aber aufgrund von Protesten vor Ort stimmt der Gemeinderat gegen das Vorhaben – es zerschlägt sich. Zwei Jahre später kommt ein Investor von außen, schließt Verträge mit Flächeneigentümern und plant einen Windpark in der doppelten Größe, der nicht nur die ursprünglichen, eher landschaftsverträglichen Standorte, sondern auch im Hinblick auf die besondere Landschaft in K. schwierigere Standorte umfasst. Aufgrund der Erfahrungen, die der Bürgermeister gemacht hat, lehnt der Projektierer jegliche Verhandlung ab und pocht auf seine gesetzlichen Rechte.

Zusammenfassend kann festgehalten werden, dass strukturelle, kommunikative und soziokulturelle Aspekte dazu führen, dass die behördlichen Verfahren ihrer Aufgabe, Konflikte konstruktiv zu regulieren, in bestimmten Situationen nicht nachkommen können.""",
        "source": "Vorschläge zur Verbesserung der Planungs- und Genehmigungsverfahren, 2016, Seite 30-33",
        "category": "communication"
    },
]

