"""
SPEED2ZERO Whitepaper - Chunked Document
Auto-generated to match Klimastrategie format
Generated for Windpark Lindenberg Assistant integration
"""

pdf_documents = [
    {
        "content": "Information Gekoppelte Herausforderungen fuer die Schweiz: Schnittstellen im Klimaschutz, Biodiversitaetsschutz, Energiesicherheit und Landschaftsschutz Whitepaper Cyril Brunner, Rebecca Lordan-Perret, Elisa Cadelli, Nadine Salzmann, Dirk N. Karger, Niklaus E. Zimmermann 17. Mai 2024 Autorinnen und Autoren: Cyril Brunner, Rebecca Lordan-Perret, Elisa Cadelli, Nadine Salzmann, Dirk Nikolaus Karger, Niklaus E. Zimmermann Der Inhalt dieses Whitepapers spiegelt ausschliesslich das Fachwissen der Autorinnen und Autoren und ihre Synthese der wissenschaftlichen Erkenntnisse wider und nicht die Meinung der aufgefuehrten Institutionen. Zitiervorschlag Brunner, C., Lordan-Perret, R., Cadelli, E., Salzmann, N., Karger, D.N., Zimmermann, N.E. Gekoppelte Herausforderungen fuer die Schweiz: Schnittstellen im Klimaschutz, Biodiversitaetsschutz, Energiesicherheit und Landschaftsschutz (ETH Zurich, white paper, 2024). https://doi.org/10.3929/ethz-b-000673411 Peer-Review: Wir danken allen Kolleginnen und Kollegen der ETH Zuerich, der Empa, der FHNW und der WSL fuer ihre hilfreichen Kommentare und Anregungen. Insbesondere moechten wir uns bei den folgenden, alphabetisch aufgefuehrten Personen bedanken: Adrienne Greet-Regamey, Gianfranco Guidati, Gabriela Hug, Anna Knoerr, Reto Knutti, Tom Kober, Christian Moretti, Bjoern Niesen, Anthony Patt, Sarah Richman, Jonas Savelsberg, Christian Schaffner, Sonia Seneviratne und Petra Sieber. Dieses Whitepaper wurde im Rahmen von SPEED2ZERO erstellt. SPEED2ZERO ist eine Joint Initiative, die von den sechs Institutionen des ETH-Bereichs gemeinsam durchgefuehrt wird. In SPEED2ZERO werden Werkzeuge, Massnahmenplaene und Technologien entwickelt, die eine nachhaltige Transformation in der Schweiz unterstuetzen. Eine Transformation, welche die internationalen und nationalen Klimaziele erfuellt, in der eine resiliente Energieversorgung gewaehrleistet ist und in der die Biodiversitaet ihren Reichtum zurueckgewinnen kann. SPEED2ZERO wurde vom ETH-Rat im Rahmen des Joint Initiatives Programms unterstuetzt. --- Page 2 --- Zusammenfassung Massnahmen gegen den Klimawandel stellen uns vor diverse Herausforderungen: Wie koennen wir gleichzeitig die Biodiversitaet erhalten, die Landschaft bewahren und die Energieversorgung sichern? Ein Beispiel fuer solche Zielkonflikte ist die bevorstehende Abstimmung ueber das Bundesgesetz ueber eine sichere Stromversorgung mit erneuerbaren Energien. Um diese Fragen wissenschaftlich zu beurteilen, hat eine Gruppe von Wissenschaftlerinnen und Wissenschaftlern mit unterschiedlichem Hintergrund im interdisziplinaeren Projekt SPEED2ZERO mit der Beteiligung von sechs Institutionen des ETH-Bereichs die Herausforderungen, Chancen und Zielkonflikte zwischen Klimaschutz, Biodiversitaetsschutz, Energiesicherheit und Landschaftsschutz analysiert. Dies ist eine Zusammenfassung der Erkenntnisse zur Unterstuetzung der Entscheidungsfindung.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 1-500"
    },
    {
        "content": "Kernaussagen Die Schweiz muss ihren Energiesektor schneller dekarbonisieren, um ihre Klimaziele zu erreichen und die Biodiversitaet zu schuetzen. Der Zustand der Biodiversitaet ist besorgniserregend. In der Schweiz sind die Ursachen fuer den Verlust der Biodiversitaet bisher hauptsaechlich nicht energiebezogen. Ohne griffige Massnahmen gegen den Klimawandel wird er voraussichtlich zu einem der Hauptfaktoren fuer den Verlust der Biodiversitaet werden. Der Klimawandel bedroht auch zunehmend Landschaften. Daher besteht eine wichtige Motivation fuer die Eindaemmung des Klimawandels darin, den daraus resultierenden Verlust der Biodiversitaet und die Auswirkungen auf die Landschaft zu begrenzen. Die Schweiz plant die Abkehr von fossilen Brenn- und Treibstoffen vor allem durch die Elektrifizierung, z.B. von Heizungen und der Mobilitaet. Die Schweiz beabsichtigt, diesen erhoehten Strombedarf durch den Ausbau der Stromerzeugung aus erneuerbaren Energien zu decken, indem sie vor allem in die Photovoltaik und den Ausbau der Wasserkraftkapazitaeten investiert. Diese dominierenden Quellen werden durch andere Technologien wie Windenergie oder Kraftwerke ergaenzt, die mit Abfall mit Kohlenstoffabscheidung und -speicherung, Biomasse, synthetischen Gasen und gruenem Wasserstoff betrieben werden. Bei jeder neuen Infrastruktur, auch fuer erneuerbare Energien, sind gewisse negative Auswirkungen unvermeidlich, und Kompromissloesungen sind zwingend. Die Wahl der Technologien fuer erneuerbare Energien und vermutlich noch wichtiger ihr Standort haben direkte Auswirkungen auf die Biodiversitaet und die Landschaft, die jedoch begrenzt werden koennen. Veraenderungen sind unvermeidlich: Nichts zu tun bedeutet nicht, dass sich nichts aendert. Nichtstun bedeutet vielmehr, dass die unvermeidlichen Veraenderungen weniger vorhersehbar und wahrscheinlich weniger wuenschenswert sein werden. Deshalb sollte die Schweiz heute bewusste Veraenderungen vornehmen, solange sie noch einige Hebel in der Hand hat, um den Wandel in eine wuenschenswerte Richtung zu lenken.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 501-1000"
    },
    {
        "content": "Negative Auswirkungen auf die Biodiversitaet koennen durch die Einhaltung von vier Leitprinzipien minimiert werden: minimale Ausdehnung, Konnektivitaet, Komplementaritaet und Nachhaltigkeit. Die aktuellen Diskussionen ueber die Auswirkungen neuer Energieinfrastrukturen auf die Biodiversitaet sind zwar wichtig, es sollte jedoch betont werden, dass solche Anlagen nicht die Hauptursache fuer den Verlust der Biodiversitaet sind und hoechstwahrscheinlich auch nie sein werden. Um den Verlust der Biodiversitaet im Allgemeinen zu bekaempfen, sollte die Schweiz auch die anderen Ursachen besprechen und angehen. --- Page 3 --- Einleitung In den naechsten Jahren wird die Schweizer Bevoelkerung verschiedene wichtige Entscheidungen treffen muessen, um die vielschichtige Herausforderung der Eindaemmung des Klimawandels zu bewaeltigen: Wie kann gleichzeitig die biologische Vielfalt geschuetzt, die Landschaft erhalten und die Energieversorgung gesichert werden? In diesem Whitepaper diskutieren wir einige der impliziten und notwendigen Abwaegungen, mit denen sich die Schweiz auseinandersetzen muss, und wie die dringende Energiewende zur Bewaeltigung des Klimawandels angegangen werden kann, um die Auswirkungen auf die Biodiversitaet und die Landschaft zu begrenzen. Unzureichendes Tempo fuer die gesetzten Ziele Waehren die demokratisch festgelegten nationalen Ziele in der Schweiz in einer Bandbreite liegen, um die ratifizierten internationalen Klimaziele zu erreichen, sind die bisherigen Massnahmen der Schweiz zur Reduktion ihrer Treibhausgasemissionen ungenuegend. Ein wichtiger Weg zur Reduktion dieser Emissionen ist unter anderem die Abkehr von fossilen Energietraegern durch Elektrifizierung, z.B. des Verkehrs oder der Heizungen, in Kombination mit Strom aus emissionsarmen Quellen. Die Stromerzeugung in der Schweiz ist bereits seit vielen Jahrzehnten fast vollstaendig dekarbonisiert. Der Rest des Energiesystems ist jedoch nach wie vor stark von fossilen Energietraegern abhaengig, z.B. Heizungen und Verkehr.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 1001-1500"
    },
    {
        "content": "Die Umstellung von fossilen Brennstoffen auf Elektrizitaet und die wachsende Bevoelkerung werden die Stromnachfrage in der Schweiz je nach Aktionsplan um etwa ein Drittel von heute 58.5 TWh/Jahr auf 70-90 TWh/Jahr im Jahr 2050 erhoehen. Die Schweiz will diese Nachfragesteigerung mit erneuerbaren Energiequellen wie Photovoltaik, Wasserkraft und Windkraft decken. Diese Energiequellen muessen mit besser zuschaltbaren Technologien wie Kraftwerken kombiniert werden, betrieben mit Abfall mit Kohlenstoffabscheidung und -speicherung, Biomasse, synthetischen Gasen oder gruenem Wasserstoff. Aufgrund der derzeitigen rechtlichen und finanziellen Lage und der fuer den Bau erforderlichen Zeit werden neue Kernkraftwerke bis 2050 voraussichtlich nicht relevant sein. Der Aufbau eines neuen, auf erneuerbare Ressourcen basierenden Energiesystems erfordert kontinuierliche und umfangreiche Investitionen, die Jahrzehnte dauern werden. Mit anderen Worten: Um die Dekarbonisierung bis 2050 zu erreichen, muss die Schweiz jetzt proaktiv handeln. Bis 2022 war der jaehrliche Zuwachs an erneuerbaren Energien zu langsam, manchmal sogar deutlich zu langsam, um die allgemeinen Dekarbonisierungsziele zu erreichen. Fuer die zuvor beobachtete Zurueckhaltung bei der Anschaffung erneuerbarer Energien gibt es verschiedene Gruende, darunter die Dynamik des derzeitigen Systems, hohe Vorlaufkosten, fehlende Anreize und eine komplizierte gesellschaftliche Akzeptanz. Ein weiterer Teil dieser Zurueckhaltung ergibt sich aus der Sorge um eine Ausweitung der Energieerzeugung auf Kosten der Biodiversitaet und der Landschaft. Weltweit, aber auch in der Schweiz, nimmt die Biodiversitaet in alarmierendem Ausmass ab.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 1501-2000"
    },
    {
        "content": "Die Haelfte der Lebensraeume und ein Drittel der Arten in der Schweiz sind bedroht. Mit dem Rueckgang der Populationen von Arten geht auch die genetische Vielfalt verloren. Die Verluste setzen sich auf anderen Ebenen der Biodiversitaet fort. Eine der wirksamsten Schutzmassnahmen ist es, der Biodiversitaet mehr Raum zu geben. Bislang sind nur 13.4% der Flaeche der Schweiz geschuetzt, wobei 17% angestrebt werden. Damit wird das auf der COP15 vereinbarte und von der Wissenschaft empfohlene Ziel von 30% bis 2030 nicht erreicht. Entwicklungen ausserhalb des Energiesektors wie die Zersiedelung und die Landwirtschaft sind die groessten Treiber des Biodiversitaetsverlustes. Im Energiesektor liegt der wichtigste, aber nicht der einzige, negative Einfluss in der raschen Erderwaermung, die durch Treibhausgasemissionen verursacht wird. --- Page 4 --- Untaetigkeit hat ihren Preis Mit einer Erwaermung von 2.8 Grad Celsius hat sich die Schweiz seit dem Zeitraum 1871-1900 mehr als doppelt so stark erwaermt wie der globale Durchschnitt. Die gegenwaertige und kuenftige rasche Erwaermung und die Veraenderung anderer wichtiger Klimavariablen wie der Niederschlaege werden die natuerlichen Oekosysteme schaedigen und die Biodiversitaet direkt verringern. Waehren einheimische Arten verschwinden, werden nicht-einheimische Arten ihren Platz einnehmen. Einige von ihnen koennen invasiv werden, was die Oekosysteme noch weiter beeintraechtigt.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 2001-2500"
    },
    {
        "content": "Der Temperaturanstieg hat und wird auch in Zukunft die Landschaft veraendern, z.B. durch das Verschwinden von Gletschern, destabilisierte Haenge infolge des auftauenden Permafrosts oder abgestorbene, ausgetrocknete Waelder. Eine der Hauptbegruendungen fuer die Begrenzung der globalen Erwaermung auf 1.5 Grad Celsius ist die Vermeidung irreversibler Schaeden an der globalen Biodiversitaet. Bei einer Erwaermung von 2 Grad Celsius wuerde die globale Erwaermung zum groessten Treiber fuer den Verlust der Biodiversitaet werden. Daher wird jede der realisierbaren Netto-Null-Strategien zum Schutz der Biodiversitaet beitragen, indem sie den Klimawandel abschwaecht. Andererseits sind Klimaschutzmassnahmen, auch wenn sie die Biodiversitaet und die Landschaft auf ueberregionaler Ebene erhalten, nicht frei von negativen Auswirkungen auf lokaler oder regionaler Ebene. In den meisten Faellen lassen sich die Auswirkungen neuer erneuerbarer Infrastrukturen auf die Biodiversitaet am besten minimieren, wenn sie auf bestehenden Infrastrukturen wie Gebaeuden, Strassen oder Lawinenschutz platziert werden, oder dort, wo die Biodiversitaet bereits stark beeintraechtigt ist, wie z.B. auf bewirtschafteten Flaechen. Diese Standorte geniessen auch eine groessere soziale Akzeptanz. Dies ist jedoch nicht in jedem Fall moeglich oder zwangsläufig optimal. So entsteht ein Spannungsverhaeltnis zwischen der Minimierung der insgesamt gewidmeten Flaeche und der Vermeidung sensibler Gebiete.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 2501-3000"
    },
    {
        "content": "--- Page 5 --- Die Kosten des Handelns und Nichthandelns sind weit mehr als nur finanziell. Ohne einen Markt oder ein monetaeres Aequivalent ist es schwierig, zwischen konkurrierenden Optionen zu waehlen oder eine umfassende politische Entscheidung zu treffen. Letztlich ist die Bezifferung von Optionen mit einem einzigen Kostenwert hoechst unsicher. Dennoch gibt es immer mehr Literatur, die versucht, spezifische Schaeden im Zusammenhang mit dem Klimawandel zu quantifizieren, einschliesslich indirekter Schaeden wie die Verlangsamung des Wirtschaftswachstums. Trotz unvollkommener und unvollstaendiger Schaetzungen dieser Schaeden kann im Vergleich zu den Kosten der Eindaemmung des Klimawandels ueberzeugend argumentiert werden, dass auf globaler Ebene die Vorteile der Eindaemmung des Klimawandels wahrscheinlich groesser sind als die Kosten der Dekarbonisierung. Diese Argumentation wird noch verstaerkt, wenn die Nebeneffekte der Dekarbonisierung beruecksichtigt werden, z.B. bessere Allgemeingesundheit aufgrund geringerer Luftverschmutzung, geringere Auswirkungen auf die Biodiversitaet und bessere Boden- und Wasserqualitaet. Es mag paradox klingen, aber nichts zu tun bedeutet nicht, dass sich nichts aendern wird. Untaetigkeit bedeutet vielmehr, dass unvermeidliche Veraenderungen weniger vorhersehbar und wahrscheinlich weniger wuenschenswert sind. Deshalb sollte die Schweiz heute bewusste Veraenderungen vornehmen, solange sie noch einige Hebel in der Hand hat, um den Wandel in eine wuenschenswerte Richtung zu lenken.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 3001-3500"
    },
    {
        "content": "Nutzen maximieren, Nebenwirkungen minimieren Eine klimaneutrale Schweiz bis 2050 ist technisch und wirtschaftlich moeglich. Das Wissen, die Technologien und die Finanzierungsmechanismen sind vorhanden. Studien haben gezeigt, dass der Schweizer Finanzplatz den Investitionsbedarf fuer ein Netto-Null-Ziel decken kann. Der politische Wille der Schweiz ist jedoch wechselhaft. Es gibt viele moegliche Wege, um die Klimaziele zu erreichen. Im Idealfall waehlt die Schweiz einen Energiepfad, der auch ihre Biodiversitaet und ihre Landschaft schuetzt. Die Biodiversitaet ist nicht gleichmaessig ueber die Landschaft verteilt. Ein tragfaehiger Weg, der die groessten negativen Auswirkungen auf die Biodiversitaet und die Leistungen, die die Biodiversitaet oder funktionierende Oekosysteme fuer die Gesellschaft erbringen, vermeidet, erfordert sorgfaeltige Optimierungsverfahren. 1) Das Prinzip des minimalen Ausmasses: Erfolgreicher Biodiversitaetsschutz erfordert ein minimales Flaechenausmass. Die 30 by 30-Regel, die den Schutz von 30% der Landesflaeche bis 2030 fordert, ist ein guter Kompromiss, um eine ausreichende Flaeche fuer den Schutz der hochkomplexen Biodiversitaet in der Schweiz zu erreichen.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 3501-4000"
    },
    {
        "content": "--- Page 6 --- Die zahlreichen Arten in der Schweiz bewohnen viele verschiedene Lebensraeume, von nass bis trocken, von warm bis kalt, von Grasland bis Wald. Zudem unterscheiden sich aehnliche Lebensraeume in zwei verschiedenen Regionen in ihrer Artenzusammensetzung. Daher kann man nicht nur ein kleines Gebiet schuetzen, da es nicht genuegend Raum fuer das Ueberleben vieler Arten bietet und nicht viele verschiedene Lebensraeume enthaelt. Ausserdem ist es nicht ratsam, ein groesseres Gebiet nur in einer Region zu schuetzen, auch wenn es viele Lebensraeume enthaelt. Bei diesem Ansatz wuerden viele Arten aus anderen Regionen ungeschuetzt bleiben. 2) Prinzip der Komplementaritaet: Gebiete, die von Arten bewohnt werden, die durch bestehende Schutzgebiete nicht gut geschuetzt sind, sollten fuer neue Bauten gemieden werden. Es muss geprueft werden, inwieweit die Biodiversitaet in der Schweiz durch die bestehenden Schutzgebiete erhalten wird. Danach muessen zusaetzliche Schutzgebiete sorgfaeltig ausgewaehlt werden, um ein Netzwerk zu schaffen, das die Zahl der geschuetzten Arten maximiert. Installationen neuer Bauten in Gebieten sind weniger schaedlich, wenn die Gebiete vor allem Arten beherbergen, die bereits gut geschuetzt sind. 3) Prinzip der Konnektivitaet: Gebiete, die im Idealfall bestehende Schutzgebiete innerhalb der Migrationsdistanz der meisten Arten verbinden, sollten fuer neue Bauvorhaben vermieden werden.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 4001-4500"
    },
    {
        "content": "Der fortschreitende Klimawandel zwingt viele Arten zur Migration, um zu ueberleben. Die anhaltende Erwaermung und die haeufig damit verbundene Austrocknung zwingen die Arten, neue Standorte zu finden, die ihren Anforderungen an Temperatur und Feuchtigkeit entsprechen. Infolgedessen wandern die Arten ab, oft in hoehere Lagen oder an Standorte, die zuvor zu feucht oder zu kalt waren. Sowohl die Migration als natuerlicher Teil des Lebens einer Art als auch die Migration aufgrund von Klimaveraenderungen erfordert ausreichend Platz. Die meisten Arten koennen nicht einfach quer durch die Landschaft wandern. Stattdessen neigen Arten dazu, entlang von Flecken ihres bevorzugten Lebensraums zu wandern. Der nationale Ansatz der oekologischen Infrastruktur, der sich derzeit in den Kantonen der Schweiz in der Planungsphase befindet, ist ein hervorragendes Instrument zur Unterstuetzung des Konnektivitaetsprinzips. 4) Nachhaltigkeitsprinzip: Ein erfolgreicher Schutz der Biodiversitaet und die Erhaltung funktionierender Oekosysteme leisten einen wichtigen Beitrag zur Eindaemmung des Klimawandels. Die Vegetationsdecke der Schweiz bindet grosse Mengen an Kohlenstoff. Pflanzen sterben staendig ab und regenerieren sich. Wenn sie absterben, geben sie Kohlenstoff an die Atmosphaere ab. Wenn sie wachsen, entziehen sie der Atmosphaere Kohlenstoff.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 4501-5000"
    },
    {
        "content": "Weltweit hat die Vegetation rund 30% der menschlichen CO2-Emissionen absorbiert und damit zur Abschwaechung des Klimawandels beigetragen. Der fortschreitende Klimawandel fuehrt dazu, dass die Oekosysteme deutliche Stresssymptome zeigen. Die Walliser Foehrenwaelder und die Buchenwaelder im Mittelland zeigen ein zunehmendes Absterben der vorherrschenden Baumarten als Reaktion auf immer staerkere Duerreereignisse. Massives Absterben und das geringere Wachstumspotenzial unter trockeneren Bedingungen wirken sich negativ auf das Potenzial aus, der Atmosphaere Kohlenstoff zu entziehen. Artenreichere Pflanzengemeinschaften sind gegenueber solchen negativen Einfluessen des fortschreitenden Klimawandels widerstandsfaehiger als weniger artenreiche Gemeinschaften und koennen beispielsweise auch dazu beitragen, steile Haenge zu stabilisieren und damit Naturgefahren zu mindern. Vor dem Hintergrund dieser Grundsaetze muss die Schweiz entscheiden, welche Technologien und Quellen sie fuer ihre Stromversorgung nutzen will, und vor allem, wo sie diese ansiedeln will. --- Page 7 --- Die meisten Forschenden sind sich einig, dass die Schweiz in erster Linie auf Wasserkraft, Photovoltaik und in geringerem Masse auf Importe setzen wird, um die demokratisch beschlossene Energiewende zu erreichen. Zusaetzlich wird die Schweiz auch auf eine Kombination von Windenergie und thermischen Erzeugern setzen, doch wird der Anteil dieser Technologien im Vergleich zu Wasserkraft und Photovoltaik gering sein.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 5001-5500"
    },
    {
        "content": "Die meisten Szenarioergebnisse deuten darauf hin, dass die Schweiz bis 2050 rund 50% ihres Stroms mit Wasserkraft erzeugen wird, waehrend der Anteil der Solarenergie an der kuenftigen Stromnachfrage rund 40% betragen wird. Ueblicherweise wird der meiste Strom der Wasserkraft im Fruehjahr und Sommer aus der schmelzenden Schneedecke und den Gletschern gewonnen. Die Solarenergie erzeugt den meisten Strom im Sommer, wenn die Tage lang sind. Alle diese Stromquellen produzieren zwar auch im Winter, vor allem in den Bergregionen, doch ist die Stromnachfrage in Europa im Winter ebenfalls hoeher. Daher muss dieses Stromangebot durch Stromhandel, Technologien, die im Winter mehr produzieren, und oder durch eine zuschaltbare Erzeugung ergaenzt werden, z.B. Windenergie, Solarenergie in grossen Hoehen, modernisierte Wasserkraftwerke oder Waermekraftwerke mit Erdgas mit Kohlenstoffabscheidung und -speicherung, Biogas oder Wasserstoff. Wissenschaftliche Akzeptanzuntersuchungen zu neuen Infrastrukturen fuer erneuerbare Energien kommen zu zwei Hauptaussagen: Erstens werden erneuerbare Energieanlagen in der Schweiz in bereits ueberbauten Gebieten besser bewertet. Zweitens ist die gesellschaftspolitische Akzeptanz hoeher, wenn die Energieanlagen verdichtet und nicht ueber die Landschaft verteilt gebaut werden.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 5501-6000"
    },
    {
        "content": "Diese beiden Punkte stehen auch im Einklang mit den Leitprinzipien fuer den Schutz der Biodiversitaet. Darueber hinaus wurde in Workshops mit diversen Interessengruppen eine Reihe relevanter Kriterien fuer eine biodiversitaets- und landschaftsfreundliche Planung neuer erneuerbarer Energien ausgearbeitet. Erneuerbare Energien und ihre Auswirkungen Angesichts der diversen Optionen im Hinblick auf erneuerbare Energiequellen ist es sinnvoll, diese auf ihr Energiepotenzial, ihre Auswirkungen auf die Landschaft und die Biodiversitaet in der Schweiz zu untersuchen. Die Wasserkraft liefert etwa zwei Drittel des aktuellen Schweizer Strommixes, hat aber erhebliche Auswirkungen auf die Biodiversitaet und die Landschaft, und es gibt wenig Flexibilitaet bei der Wahl des Standorts dieser Infrastrukturen. Diese Auswirkungen variieren je nach Art der Wasserkraftanlage: Laufwasserkraft, Speicherkraft oder Pumpspeicherkraft. Das Schweizerische Gewaesserschutzgesetz verlangt zum Beispiel die Wiederherstellung der Fischdurchgaengigkeit in Fluessen, was wiederum durch neue Laufwasserkraftwerke negativ beeintraechtigt wuerde. Generell sind Laufwasserkraftwerke schaedlich fuer laichende Fische und beeintraechtigen die Bewegung von naehrstoffreichem Sediment stark.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 6001-6500"
    },
    {
        "content": "--- Page 8 --- Speicherseen und Pumpspeicherkraftwerke schaden der Biodiversitaet vor allem durch Ueberflutung oder Trockenlegung beziehungsweise Abschwemmung von Lebensraeumen, in denen Arten brueten oder wachsen. Wasserkraft traegt auch zu Erosion und Instabilitaet der Uferlinie bei, was ebenfalls zum Verlust der Biodiversitaet beitragen und moeglicherweise Erdrutsche oder Felsstuerze ausloesen kann. Nach Angaben des Bundesamts fuer Energie hat die Schweiz mit ihren landesweit fast 700 Wasserkraftwerken mit einer Leistung von mehr als 300 MW bereits einen Grossteil ihres Wasserkraftpotenzials ausgeschoepft. Diese Anlagen koennen rund 37 TWh pro Jahr oder 60% des gesamten Strombedarfs produzieren. Dennoch hat sich die Schweiz in der Energiestrategie verpflichtet, mehr Strom aus Wasserkraft zu produzieren. In Zusammenarbeit mit den relevanten Interessengruppen waehlte die Schweizer Regierung schliesslich 15 Wasserkraftprojekte aus, unter Beruecksichtigung der prognostizierten Auswirkungen auf die Biodiversitaet und die Landschaft sowie des Umfangs der zusaetzlichen Kapazitaet. Die ausgewaehlten Projekte werden die Winterproduktion um 2 TWh erhoehen. Bei den meisten dieser Projekte handelt es sich um Erweiterungen bestehender Anlagen, es sind jedoch auch zwei neue Anlagen am Gorner- und Triftgletscher in Planung.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 6501-7000"
    },
    {
        "content": "Was die gesellschaftliche Akzeptanz betrifft, so sind die bestehenden Wasserkraftwerke weitgehend unumstritten, auch weil sich die Bevoelkerung an sie gewoehnt hat und die Gemeinden oft finanziell davon profitieren. Einige Schweizer Staudämme gelten sogar als Wahrzeichen und sind wichtig fuer den Tourismus. Neue Anlagen stossen jedoch nicht auf die gleiche Akzeptanz. Einige Studien deuten darauf hin, dass oekologische Kompensationen, wie die Renaturierung lokaler Baeche in der Region, einen guenstigen Einfluss auf die Akzeptanz haben. Darueber hinaus koennen Mehrzwecknutzungen von Wasserkraftwerken die Akzeptanz regional und national erhoehen, z.B. fuer landwirtschaftliche Bewaesserung, Trinkwasserversorgung, Hochwasserschutz oder als touristische Attraktionen. Das grosse Solarpotenzial der Schweiz wird gerade erst erschlossen. Im Jahr 2023 wurden in der Schweiz 1500 MW an neuer Solar-PV-Leistung installiert, und die gesamte installierte Leistung erreichte 6200 MW, die 6.4 TWh produzierten. Fast alle aktuellen Szenarien gehen davon aus, dass der Grossteil dieser neuen Kapazitaeten aus Solaranlagen auf Daechern und an Fassaden stammen wird, da das Investitionsrisiko gering, die gesellschaftliche Akzeptanz hoch ist und der Nutzer vom Eigenverbrauch profitieren kann. In der Tat befindet sich die ueberwiegende Mehrheit der bestehenden Solar-PV auf Gebaeuden.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 7001-7500"
    },
    {
        "content": "Das PV-Potenzial auf Daechern wird jedoch oft nur teilweise ausgeschoepft, was eher auf private finanzielle Vorteile als auf gesellschaftliche Beduerfnisse zurueckzufuehren ist. Wenn aber jegliche private Investition nur einen Teil des Solarpotenzials auf den eigenen Daechern ausschoepft, wird die installierte Leistung auf Daechern nicht ausreichen, um die Schweizer Ziele zu erreichen, und andere Standorte oder Typen von PV muessen in groesserem Umfang genutzt werden. Eine hohe Akzeptanz besteht auch fuer PV auf anderen Anlagen wie Laermschutzwaenden entlang von Autobahnen oder anderen Funktionsbauten wie Lawinenverbauungen. Auch Synergien durch multifunktionale Landnutzung sind denkbar, wenn zum Beispiel Landwirtschafts- oder Weideflaechen mit PV-Anlagen weiterhin genutzt werden koennen. Die Schweiz ist sehr restriktiv gegenueber Freiflaechenanlagen, waehrend in der Europaeischen Union drei Viertel des erzeugten Solarstroms aus Freiflaechenanlagen stammen. Freiflaechenanlagen koennen schneller errichtet werden und sind in der Regel kostenguenstiger, waehrend das Land in vielen Faellen weiterhin fuer seinen urspruenglichen Zweck genutzt werden kann. Freiflaechensysteme werden fuer die Erreichung der nationalen Ziele wichtig sein.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 7501-8000"
    },
    {
        "content": "--- Page 9 --- Weitere vorgeschlagene Standorte sind Industrie- und Landwirtschaftsstandorte sowie, besonders umstritten, Standorte in den Alpen. PV-Paneele auf Daechern oder in bereits bebauten Gebieten stehen im Einklang mit den Leitprinzipien fuer den Schutz der Biodiversitaet, da sie minimale bis keine negativen Auswirkungen auf die Biodiversitaet haben. Es gibt derzeit nur wenig Literatur, aber bisher keine Belege dafuer, dass Solarinfrastruktur auf landwirtschaftlich genutzten Flaechen negative Auswirkungen auf die Biodiversitaet hat. Alpine PV hat den Vorteil, dass sie im Winter mehr Strom produziert, wenn die kuenftige Stromerzeugung in der Schweiz wahrscheinlich einen hoeheren Wert haben wird. Der alpine Standort ist jedoch sowohl in Bezug auf die Biodiversitaet als auch auf die Landschaft sensibel. Auf nach Sueden ausgerichteten Haengen koennten Paneele das Sonnenlicht vom Boden verdecken und den Pflanzenreichtum und oder die Artenzusammensetzung veraendern. Je nach Groesse und Platzierung der Paneele koennten sich auch die Wander- und Weideflaechen fuer Tiere verringern. Auch wenn sich die Photovoltaik auf die Artenverteilung auswirken kann, muss darauf hingewiesen werden, dass viele der geplanten alpinen PV-Standorte nicht in unberuehrten natuerlichen Lebensraeumen liegen, sondern auf bewirtschafteten Flaechen, wo die biologische Vielfalt bereits stark beeintraechtigt ist.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 8001-8500"
    },
    {
        "content": "Aus landschaftlicher Sicht wird die gesellschaftliche Akzeptanz von PV-Paneelen in den Bergen als geringer eingeschaetzt als auf Gebaeuden, aber eine kuerzlich durchgefuehrte Umfrage deutet darauf hin, dass sich dies aendert, da etwa 60% der Schweizer Bevoelkerung und 56% der lokalen Bevoelkerung solche Anlagen befuerworten. Etwa zwei Drittel der vorgeschlagenen alpinen PV-Projekte wurden bei lokalen Abstimmungen fuer gut befunden. Eine Moeglichkeit besteht darin, PV-Paneele auf Lawinenverbauungen zu montieren, um die visuellen Auswirkungen dieser Infrastrukturen zu verringern. Letzteres ist jedoch auch mit technischen Problemen und hohen finanziellen Kosten sowie mit einer potenziellen Beeintraechtigung der primaeren Schutzfunktion der Lawinenverbauung verbunden. Unabhaengig davon erwarten die meisten Forschenden keine alpinen PV-Investitionen ohne erhebliche staatliche Unterstuetzung. Waehren in allen Forschungsszenarien fuer die Schweiz die Photovoltaik und die Wasserkraft den groessten Teil des Stroms liefern werden, setzen diese Szenarien ausserdem auch auf Technologien wie Windenergie oder Kraftwerke betrieben mit Abfall oder erneuerbaren Gasen. Die Windenergie produziert derzeit etwa 0.14 TWh pro Jahr aus 40 Windkraftanlagen. Laut der juengsten Studie des Bundesamts fuer Energie betraegt das gesamte technische Potenzial der Windkraft in der Schweiz 29.5 TWh pro Jahr. Die Windenergie produziert den groessten Teil ihres jaehrlichen Stroms im Winter.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 8501-9000"
    },
    {
        "content": "Aus Biodiversitaetsperspektive hat die Windenergie insgesamt nur geringe negative Auswirkungen. Allerdings sind die Folgen fuer bestimmte Arten ausgepraegt, in der Schweiz vor allem fuer Voegel und Fledermaeuse. Diese Belastung kann durch eine sorgfaeltige Planung von Windkraftanlagenstandorten in sicherer Entfernung zu Vogelbrutplaetzen oder Zugrouten gefaehrdeter Arten und durch aktive Massnahmen wie die automatische Erkennung von herannahenden Voegeln zur voruebergehenden Abschaltung der Windkraftanlage reduziert werden. Die Akzeptanz von Windkraftanlagen ist vor allem aufgrund ihrer hohen Sichtbarkeit insbesondere im Flachland in der Naehe von Ballungszentren begrenzt. Finanzielle Vorteile, die im Verhaeltnis zur erzeugten Strommenge verteilt werden, koennen die Akzeptanz von Windenergieanlagen erhoehen und Anreize fuer die lokale Bevoelkerung schaffen. Auch Synergien durch multifunktionale Landnutzung sind denkbar, wenn beispielsweise landwirtschaftliche Flaechen ungeachtet der Windkraftanlagen genutzt werden. Einige Untersuchungen kommen zu dem Ergebnis, dass eine Kombination von Windenergie mit Photovoltaik die Akzeptanz bis zu einem gewissen Grad erhoeht. --- Page 10 --- Abfallverwertungsanlagen und Kraftwerke betrieben mit synthetischen Gasen, einschliesslich Biogas und Wasserstoff, koennen sogenannte steuerbare, also zuschaltbare Energie sein.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 9001-9500"
    },
    {
        "content": "Das heisst, Elektrizitaet kann immer dann produziert werden, wenn sie benoetigt wird, unabhaengig von Wetter oder Jahreszeit. Es besteht Uneinigkeit darueber, welche Rolle synthetische Brennstoffe und Wasserstoff spielen werden oder woher diese Brennstoffe kommen sollen. Nicht nur koennen Stromimporte die Verbrennung von synthetischem Gas im Inland ersetzen, sondern auch die Einfuhr synthetischer Brennstoffe selbst kann dazu fuehren, dass die Schweiz verbraucht statt produziert. Ein Grossteil der Bedenken ruehrt von der Ungewissheit ueber die kuenftigen Kosten von Wasserstoff und synthetischen Brennstoffen, die stark von Entscheidungen und Investitionen im Ausland bestimmt werden. Die Schweiz nutzt ihre Abfaelle, um sowohl Waerme als auch Strom zu erzeugen. Im Jahr 2019 produzierten diese Anlagen etwa 4 TWh Waerme und 1.8 TWh Strom. Diese Anlagen trugen auch 5% zu den Treibhausgasemissionen der Schweiz im Jahr 2022 bei. Gemaess den Plaenen des Bundesrates sollen jedoch an den 29 Kehrichtverbrennungsanlagen in der Schweiz Technologien zur Kohlenstoffabscheidung und -speicherung eingesetzt werden. Wenn die bisherigen Tendenzen mit diesen Anlagen bestehen bleiben, koennte die Energieerzeugung aus Abfaellen im Laufe des Jahrhunderts aufgrund des gestiegenen Verbrauchs zunehmen, obwohl Effizienz- und Kreislaufmassnahmen diesen Anstieg abschwaechen koennten.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 9501-10000"
    },
    {
        "content": "Wenn ihre CO2-Emissionen begrenzt werden, ist es unwahrscheinlich, dass diese Infrastrukturen grosse Auswirkungen auf die Biodiversitaet und die Landschaft haben. Diese Waermekraftwerke sind gross und zentralisiert und befinden sich in der Regel in der Naehe des Ortes, an dem der Energiebedarf anfaellt. Daher kann man davon ausgehen, dass Standorte, die grosse Anlagen in der Naehe von Bevoelkerungszentren vorweisen, wahrscheinlich bereits dicht besiedelt sind oder bereits eine Erzeugungsanlage beherbergen. Bestehende Kehrichtverbrennungsanlagen sind in der Schweiz weitgehend akzeptiert, doch die Nutzung von Biogasanlagen ist bisher nicht weit verbreitet. Studien der WSL haben gezeigt, dass Landwirtschaftsbetriebe eher bereit waeren, in Biogasanlagen zu investieren, wenn sie eine hoehere Verguetung fuer die produzierte Energieform erhalten wuerden. Auch ziehen sie es vor, eigene Anlagen zu besitzen, anstatt groessere Anlagen gemeinsam mit anderen Betrieben zu bauen. Aus energiepolitischer Sicht sind zentrale Anlagen jedoch sinnvoll, da sie effizienter betrieben werden koennen und die Einspeisung des Biogases vereinfachen, da die meisten Betriebe keine Gasleitung in der Naehe haben. Die landwirtschaftliche Biogaserzeugung koennte demnach ausgebaut werden, wenn Gemeinden, landwirtschaftliche Genossenschaften und oder Energieversorgungsunternehmen einen solchen Ausbau foerdern und koordinieren wuerden.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 10001-10500"
    },
    {
        "content": "--- Page 11 --- Dies wuerde den Koordinationsaufwand fuer die Betriebe verringern und Gemeinschaftsanlagen fuer sie attraktiver machen. Unabhaengig von der Energiediskussion sollte die Schweiz die Biodiversitaet aktiv schuetzen und erhalten. Die aktuelle Debatte ueber die Auswirkungen neuer erneuerbarer Energieanlagen auf die Biodiversitaet und das Landschaftsbild ist wichtig. Es sollte jedoch betont werden, dass solche Anlagen nicht die Hauptursache fuer den Verlust der Biodiversitaet sind und hoechstwahrscheinlich auch nie sein werden. Neben vielen anderen wichtigen Oekosystemleistungen bieten Oekosysteme mit intakter Biodiversitaet Schutz vor den Auswirkungen der globalen Erwaermung und sind daher ein wichtiger Aspekt der Eindaemmung des Klimawandels. Der anhaltende Verlust der Biodiversitaet, den wir in den letzten Jahrzehnten beobachten konnten, stellt eine grosse Bedrohung fuer unsere Gesellschaft dar, sowohl auf lokaler als auch auf globaler Ebene. Um einen weiteren Verlust zu verhindern, muessen wir unsere politischen Diskussionen ausweiten und auch die Anwendung herkoemmlicher Praktiken kritisch ueberpruefen, die die Biodiversitaet derzeit stark unter Druck setzen.",
        "source": "SPEED2ZERO_Whitepaper",
        "category": "scientific_summary",
        "page_range": "Words 10501-11000"
    }
]
